### ISSUE TITLE
Why the parameter type in Gauge.Update() is int64 not float64?

### ISSUE THREAD

**Issue by xiaogaozi** [uber/jaeger-lib#18]
This will restrict us collect float number when use Gauge

**Comment by xiaogaozi** [comment]
@yurishkuro Could you see this issue sometime?

**Comment by black-adder** [comment]
May I ask what the use case is? Although we do agree that we should be using float64 instead of int64, jaeger-lib metrics is only used internally by jaeger and jaeger-client-go. Are you planning on writing a new metrics factory that uses float64 gauges only?

**Comment by yurishkuro** [comment]
+1 to @black-adder point. At the moment we don't have any internal use cases for float64 gauges, and for historical reasons the metrics lib we're binding to internally only supported int64 (it has now changed, so we can upgrade to float64).

**Comment by xiaogaozi** [comment]
Actually I use [metrics](https://github.com/uber/jaeger-lib/tree/master/metrics) package as a fundamental library to define metrics and record metrics. I like [the way](https://github.com/uber/jaeger-client-go/blob/master/metrics.go) jaeger-lib define metrics. So my library won't rely on specific metrics library, i.e. the user of my library could use any metrics library they want, as long as it implements [`Factory`](https://github.com/uber/jaeger-lib/blob/master/metrics/factory.go) interface. This is my use case.

Only support int64 has large restriction to the user to record metrics, e.g. if I wanna record ratio, it could be float number.

**Comment by yurishkuro** [comment]
@xiaogaozi Have you considered using go-kit instead? It's a general purpose abstraction over different metrics. There are a few issues in it to make the API look even more like jaeger-lib.

**Comment by xiaogaozi** [comment]
Yeah, go-kit is awesome. But in my understanding, go-kit and tally is the same thing, but jaeger-lib not.   jaeger-lib is a general purpose wrapper on top of go-kit/tally. That's my want.

**Comment by yurishkuro** [comment]
> jaeger-lib is a general purpose wrapper on top of go-kit/tally

it is indeed a wrapper, but it was not meant to be a standalone reusable library. It's an internal API used by Jaeger components. The only reason it is in a separate repository is because we wanted to share it between Jaeger backend and Go client. In particular, this library is not versioned and we do not provide *any guarantee of stable APIs* (I just updated the README).

You are, of course, free to use it if you're ok with these caveats. As for changing the gauge to float64, we may do it in the future, but it is a breaking change for jaeger-client-go.

**Comment by xiaogaozi** [comment]
I understand and I know the risk to use an internal library. I think this issue could close.

BTW, thank you guys for create Jaeger, it's awesome.
