### ISSUE TITLE
Tag semver release

### ISSUE THREAD

**Issue by akshayjshah** [uber/jaeger-lib#21]
Hi @yurishkuro - this repository doesn't have any releases tagged. Would you mind cutting a release so that our internal tools can pin to a reasonable semver range?

**Comment by yurishkuro** [comment]
we can, but when do our tools depend on this lib directly rather than transitively?

**Comment by akshayjshah** [comment]
go-common :)

**Comment by yurishkuro** [comment]
https://github.com/uber/jaeger-lib/releases/tag/v1.0.0

@akshayjshah will you also need us to release a new version of jaeger-client-go that's pinned to this?  Right now the client [does not specify the version](https://github.com/uber/jaeger-client-go/blob/master/glide.yaml#L31).

**Comment by akshayjshah** [comment]
No need to immediately release a new version of the client, but it's worth making the change there so that it's included in the next release.
